"use client";
import "./globals.css";
import MainContainer from "./home/MainContainer";
import store from "../store";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// import Main from "./home/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <ToastContainer />
          <MainContainer children={children} />
        </Provider>
      </body>
    </html>
  );
}
